feat: implement migration
after-school-garbage-squad/repaint-server pull request #8
Opened 2023-07-14 04:56 UTC by re-taro

close #3

2023-07-15 10:20 UTC, shiron4710 requested changes
- [ ] `lc_collate`と`lc_ctype`は`ja_JP.utf-8`で作成(難しそうなら、DB側で対応します)
- [x] テーブル名はできれば複数形で、Join tableはevents_admins
- [x] `create_at`,`update_at`ってDB側にDefaultがないのですが、Rust側で自動で更新されますか？
- [x] UUID系は全てPostgreSQLのUUID型を使う(使えなかったら`character varying(32)`で)
- [x] `event_beacon.hw_id`はunique index
- [x] `event_beacon.service_uuid`はnot null,`hw_id`はNullable
- [ ] `event_image.image_id`,`compressed_image_id`はunique index(visitor_imageの方はそのままで良いです)
- [ ] `event_image`と`visitor_image`の`image_id`,`compressed_image_id`はUUIDですか？
- [ ] `visitor.registration_id`は`character varying(4096)`

2023-07-15 11:17 UTC, re-taro commented
>  - [ ] lc_collateとlc_ctypeはja_JP.utf-8で作成(難しそうなら、DB側で対応します)

ちょい、厳しい
> - [ ] テーブル名はできれば複数形で、Join tableはevents_admins

たとえばevent_spotはevent_spots？

> - [ ] UUID系は全てPostgreSQLのUUID型を使う(使えなかったらcharacter varying(32)で)

ulidを使う想定でこの文字数のcharにしてるんだけどuuid型の方が都合が良い？

2023-07-15 11:35 UTC, shiron4710 commented
> >  - [ ] lc_collateとlc_ctypeはja_JP.utf-8で作成(難しそうなら、DB側で対応します)
> 
> ちょい、厳しい

了解です

> > - [ ] テーブル名はできれば複数形で、Join tableはevents_admins
> 
> たとえばevent_spotはevent_spots？

そんな感じです

> > - [ ] UUID系は全てPostgreSQLのUUID型を使う(使えなかったらcharacter varying(32)で)
> 
> ulidを使う想定でこの文字数のcharにしてるんだけどuuid型の方が都合が良い？

UUIDは128bitなので16進数に変換しちゃうと32桁String=char(32)になってデータ長が288bitに増えちゃうんですよね
なので128bit数値型で扱えるUUIDにしたいです
postgresqlはcharが8bitじゃなくて、任意のエンコードをした一文字分なので、UUIDみたいな文字でないものをbyte列として入れるとエンコードでエラーが出ます

2023-07-15 15:47 UTC, re-taro commented
> - [ ] event_imageとvisitor_imageのimage_id,compressed_image_idはUUIDですか？

前に議論したときの文字数をUTF-8で考えた場合で設定しました

2023-07-15 16:51 UTC, shiron4710 requested changes
インデックス周りは全て大丈夫そうです！

細かい話ですが、`events_*s`や`visitors_*s`というテーブルは、`event_*s`,`visitor_*s`でお願いします。
`events_admins`はそのままで大丈夫です。

2023-07-16 02:42 UTC, shiron4710 approved these changes

2023-07-16 02:46 UTC, merged